### PR TITLE
Bump k8s dependencies to 1.29.x

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by teddyking** [comment]
Hi there, would it be possible for someone to take a look at this and to get it approved and merged? Thanks!

**Review by takirala — APPROVED** [review]

**Comment by takirala** [comment]
@pwittrock
@yue9944882

Could you please review? thanks

**Comment by takirala** [comment]
This superceedes #102

**Comment by mrueg** [comment]
@pwittrock @yue9944882 anything I can do to help getting this change in?

**Pull request closed without merging**
