### PR TITLE
Bump k8s dependencies to 0.27.3

### PR DESCRIPTION
**Pull request by liangyuanpeng**
Bump k8s dependencies to 0.27.3, releated: 
- https://github.com/kubernetes/kubernetes/issues/119840
- https://github.com/kubernetes-sigs/apiserver-runtime/issues/93

### CODE REVIEW

**Comment by coder-wen** [comment]
hi, can we merge now ?

**Comment by trawler** [comment]
Hi @gabbifish & @yue9944882 - Would love to see this PR merged as well :) ➕

**Comment by liangyuanpeng** [comment]
Kindly ping 

@pwittrock @yue9944882

**Comment by x893675** [comment]
@liangyuanpeng 
@pwittrock 

I think this pr should be restored.
In **k8s.io/apiserver@v0.27.3 pkg/registry/generic/registry/store.go** 1343 line
```go
// CompleteWithOptions updates the store with the provided options and
// defaults common fields.
func (e *Store) CompleteWithOptions(options *generic.StoreOptions) error {
	// some code
	if e.SingularQualifiedResource.Empty() {
		return fmt.Errorf("store %#v must have a non-empty singular qualified resource", e)
	}
        // some code
```
but in **apiserver-runtime pkg/builder/rest/rest.go** 71 line not set `SingularQualifiedResource`

now use latest code, always crash

I think it should be fully tested before merge pr

**Comment by x893675** [comment]
> @liangyuanpeng @pwittrock
> 
> I think this pr should be restored. In **k8s.io/apiserver@v0.27.3 pkg/registry/generic/registry/store.go** 1343 line
> 
> ```go
> // CompleteWithOptions updates the store with the provided options and
> // defaults common fields.
> func (e *Store) CompleteWithOptions(options *generic.StoreOptions) error {
> 	// some code
> 	if e.SingularQualifiedResource.Empty() {
> 		return fmt.Errorf("store %#v must have a non-empty singular qualified resource", e)
> 	}
>         // some code
> ```
> 
> but in **apiserver-runtime pkg/builder/rest/rest.go** 71 line not set `SingularQualifiedResource`
> 
> now use latest code, always crash
> 
> I think it should be fully tested before merge pr

@yue9944882

**Pull request merged**
